### ISSUE TITLE
[What's next?] Tracking issue

### ISSUE THREAD

**Issue by ar3s3ru** [get-eventually/eventually-rs#133]
Hello, welcome to `eventually`!

As you've probably read from the [README.md], the library is in active development and we need contributors to help us growing it into a viable production-ready solution.

This issue is to track the list of upcoming features that we want to include in the future versions of the library, but for which we haven't either done any plan yet (i.e. no tracking issue, not included in any milestone).

Please, feel free to suggest any desired feature by leaving a comment in this issue, or creating a new issue in the issue tracker :partying_face: 

### List of desired features

- [ ] Support for snapshots
- [ ] Command handler support and command dispatcher
- [ ] Ergonomics of the library by introducing macros (#40)
- [ ] Process managers
- [ ] [EventStore.com] backend implementation

[README.md]: https://github.com/eventually-rs/eventually-rs#note-on-semantic-versioning
[EventStore.com]: https://www.eventstore.com/eventstoredb

**Comment by danieleades** [comment]
i see the `0.5.0` pull request. how mature is that? it looks like a *lot* of changes. Is it a complete redesign, or an evolution of the current API?

If it's the latter, maybe it's worth creating a 0.5.0 branch and making changes incrementally through pull requests? (basically i'm trying to find a way to help!)

**Comment by ar3s3ru** [comment]
> i see the `0.5.0` pull request. how mature is that? it looks like a _lot_ of changes. Is it a complete redesign, or an evolution of the current API?

It was meant to be a complete redesign, trying to get a bit of parity with the Go counterpart (which, by comparison, is far more advanced and production-ready): https://github.com/get-eventually/go-eventually

The code you see in #140 is actually the first version I was working on. I've started from scratch at least 3 times, mainly due to experimenting with the Aggregate Root modeling.

> If it's the latter, maybe it's worth creating a 0.5.0 branch and making changes incrementally through pull requests? (basically i'm trying to find a way to help!)

Help and time are all I need to get this thing going 😄 

The main hurdle in regards to this PR is figuring out the design for the Aggregate Root. Maybe we can experiment with that in a specific discussion or issue and come up with a nice solution.

Definitely need to sit down and add some issues for the v0.5.0 project. Will try to do so in the next days, probably can start kicking off the Aggreate Root discussion to get things going and gain momentum 👍🏻 

As for the changes, I would prefer to keep the main development on `master` rather than having a different branch (mainly for visibility: `master` branch is the default branch 😉 )

**Comment by danieleades** [comment]
> As for the changes, I would prefer to keep the main development on `master` rather than having a different branch (mainly for visibility: `master` branch is the default branch  )

in that case, I won't hold back making pull requests with breaking changes!

**Comment by ar3s3ru** [comment]
Closing this issue for now, as we're using the Projects feature to track issues now 👍🏻
